[features]
seeds = false
skip-lint = false
[programs.localnet]
vpl = "6JuaxB1fEN9n6ApcvRxy6avr25H8qTzGRGpT43qrCvm4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/anish/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
