pub const VAX_TOKEN_MINT: &str = "2JU4847ngmiGjuZ6m2pt3unq41GVt6WRw6wnJhVPe2oD";
pub const VAX_TOKEN_DECIMALS: u16 = 9;
pub const STAKE_PER_PIECE: u16 = 100;
pub const COST_PER_REFRIGERATION_UNIT: u16 = 10;
pub const STRING_LENGTH_PREFIX: usize = 4;
pub const STRING_CHAR_MULTIPLIER: usize = 4;
pub const ID_LENGTH: usize = STRING_LENGTH_PREFIX + (24 * STRING_CHAR_MULTIPLIER);
